module.exports = {
  resource: "/media-list/read",
  path: "/media/list:[GET]",
  httpMethod: "GET",
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    path: "",
    accountId: "",
    resourceId: "",
    stage: "",
    domainPrefix: "",
    requestId: "",
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: "",
      cognitoAuthenticationType: null,
      userArn: "",
      apiKeyId: "",
      userAgent: "",
      accountId: "",
      caller: "",
      sourceIp: "",
      accessKey: "",
      cognitoAuthenticationProvider: null,
      user: ""
    },
    domainName: "",
    resourcePath: "/media-list/read",
    httpMethod: "GET",
    extendedRequestId: "",
    apiId: ""
  },
  isBase64Encoded: false
};